service: sweet-home-app

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-2
  environment:
    tableName: ${self:custom.tableName}

custom:
  stage: ${opt:stage, self:provider.stage}
  tableName: ${self:custom.stage}-expenses
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}

functions:
  create_expense:
    handler: Lambdas/src/handler.create_expense
    events:
      - http:
          path: expenses
          method: post
  
resources:
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}